spring:
  application:
    name: auth-service

  config:
    import: optional:file:../config/.env[.properties]

  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/${AUTH_DB_NAME:auth_db}
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service_url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka